language: python

addons:
  postgresql: "9.4"

sudo: required

# Handle git submodules ourselves
git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

before_script:
  - printf "[pg_qgep]\nhost=localhost\ndbname=qgep\nuser=postgres" > ~/.pg_service.conf
  - psql -c 'CREATE DATABASE qgep;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d qgep
  - psql -c 'CREATE EXTENSION hstore;' -U postgres -d qgep
  - pg_restore -d qgep test/testdata.dump
  - $TRAVIS_BUILD_DIR/datamodel/scripts/db_setup.sh

script: $TRAVIS_BUILD_DIR/scripts/migrate.sh
