language: python

addons:
  postgresql: "9.4"

sudo: required
dist: trusty

# Handle git submodules ourselves
git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install postgresql-9.4-postgis-2.3
  - ./scripts/ci/setup_git.sh

install:
  - pip install psycopg2 --quiet
  - pip install pyyaml --quiet

before_script:
  - printf "[pg_qgep]\nhost=localhost\ndbname=qgep\nuser=postgres" > ~/.pg_service.conf
  - psql -c 'CREATE DATABASE qgep;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d qgep
  - psql -c 'CREATE EXTENSION hstore;' -U postgres -d qgep
  - pg_restore -O -d qgep data/testdata.dump
  - $TRAVIS_BUILD_DIR/datamodel/scripts/db_setup.sh &>/dev/null

script:
  - $TRAVIS_BUILD_DIR/scripts/migrate.sh

after_success:
  - $TRAVIS_BUILD_DIR/scripts/ci/deploy-demodata.sh
