language: python
dist: xenial

env:
  global:
  # DOCKER_USERNAME and # DOCKER_PASSWORD
  - secure: OlqyhM/WZiCjo7tFgr98YSk33aMIIag8mqrXaLRIEjovpAr/ZvzH1vhAVHuBE/hxwh1WkC83YmG/Co2Uf+NYl+vMIJ4QSS5D2md4l4pfQzoBq40o3Sx1i4P0X/mGERWaxY9zxPCsPZLzQoesb96POD4TafhzLn9+qFdUG5A/uc0=
  - secure: SEUsGw2m2LekrzM5fQrZ7qwcStCQSIFDX3s7PeMDIfRi+YwM49KlPhKpi1a6xqRUBlis15Uj1yqo1qm0Bs4EkK6rwNwrtRAZmN+BnvyQiCikfnbLFAk4QPgfqPtxWFJPBQgtku2avlt76q3RI/gzmcKUl+w7iF3ZiKz+Q8Zy/mM=

python:
  - 3.7
  
install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: update_ts
      script:
        - ./scripts/update_and_push_ts_files.sh
      if: branch = master and type = push

    - stage: deploy
      script:
        - ./scripts/pull_ts_and_create_project.sh
        - ./scripts/release.sh
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        skip_cleanup: true
        file: qgep.zip
        on:
          repo: QGEP/QGEP
          tags: true
          branch: master
      if: tag is present
