name: Update translations

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Update translations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python + Transifex v.3 dependencies
        run: |
          # Python
          pip install -r requirements.txt
          # Go (Transifex)
          curl -OL https://github.com/transifex/cli/releases/download/v1.3.1/tx-linux-amd64.tar.gz
          tar -xvzf tx-linux-amd64.tar.gz

      - name: Update translations
        env:
          tx_token: ${{ secrets.TX_TOKEN }}
        run: |
          TX_TOKEN=$tx_token ./scripts/update_and_push_ts_files.sh
