name: 🧪 Create Translated Project

on:
  workflow_dispatch:

jobs:
  # Run unit tests
  translate_project:
    runs-on: ubuntu-20.04
    env:
      TX_TOKEN: ${{ secrets.TX_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull translations and build project
        run: |
          export QGEP_SOURCE_DIR=$(pwd)
          curl -OL https://github.com/transifex/cli/releases/download/v1.3.1/tx-linux-amd64.tar.gz
          tar -xvzf tx-linux-amd64.tar.gz
          ./scripts/pull_ts_and_create_project.sh
      - uses: actions/upload-artifact@v2
        with:
          name: project
          path: project/
