name: Update translations

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Update translataions
    runs-on: ubuntu-latest

    env:
      TX_TOKEN: ${{ secrets.TX_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python + Transifex v.3 dependencies
        run: |
          # Python
          pip install -r requirements.txt
          # Go (Transifex)
          curl -OL https://github.com/transifex/cli/releases/download/v1.3.1/tx-linux-amd64.tar.gz
          tar -xvzf tx-linux-amd64.tar.gz

      - name: package
        run: |
          ./scripts/update_and_push_ts_files.sh
